// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V1CreateDeviceV1Request v1 create device v1 request
//
// swagger:model v1CreateDeviceV1Request
type V1CreateDeviceV1Request struct {

	// platform
	Platform string `json:"platform,omitempty"`

	// user Id
	UserID string `json:"userId,omitempty"`
}

// Validate validates this v1 create device v1 request
func (m *V1CreateDeviceV1Request) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this v1 create device v1 request based on context it is used
func (m *V1CreateDeviceV1Request) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V1CreateDeviceV1Request) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1CreateDeviceV1Request) UnmarshalBinary(b []byte) error {
	var res V1CreateDeviceV1Request
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
