// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V1UpdateDeviceV1Response v1 update device v1 response
//
// swagger:model v1UpdateDeviceV1Response
type V1UpdateDeviceV1Response struct {

	// success
	Success bool `json:"success,omitempty"`
}

// Validate validates this v1 update device v1 response
func (m *V1UpdateDeviceV1Response) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this v1 update device v1 response based on context it is used
func (m *V1UpdateDeviceV1Response) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V1UpdateDeviceV1Response) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1UpdateDeviceV1Response) UnmarshalBinary(b []byte) error {
	var res V1UpdateDeviceV1Response
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
