// Code generated by go-swagger; DO NOT EDIT.

package act_device_api_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewActDeviceAPIServiceListDevicesV1Params creates a new ActDeviceAPIServiceListDevicesV1Params object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewActDeviceAPIServiceListDevicesV1Params() *ActDeviceAPIServiceListDevicesV1Params {
	return &ActDeviceAPIServiceListDevicesV1Params{
		timeout: cr.DefaultTimeout,
	}
}

// NewActDeviceAPIServiceListDevicesV1ParamsWithTimeout creates a new ActDeviceAPIServiceListDevicesV1Params object
// with the ability to set a timeout on a request.
func NewActDeviceAPIServiceListDevicesV1ParamsWithTimeout(timeout time.Duration) *ActDeviceAPIServiceListDevicesV1Params {
	return &ActDeviceAPIServiceListDevicesV1Params{
		timeout: timeout,
	}
}

// NewActDeviceAPIServiceListDevicesV1ParamsWithContext creates a new ActDeviceAPIServiceListDevicesV1Params object
// with the ability to set a context for a request.
func NewActDeviceAPIServiceListDevicesV1ParamsWithContext(ctx context.Context) *ActDeviceAPIServiceListDevicesV1Params {
	return &ActDeviceAPIServiceListDevicesV1Params{
		Context: ctx,
	}
}

// NewActDeviceAPIServiceListDevicesV1ParamsWithHTTPClient creates a new ActDeviceAPIServiceListDevicesV1Params object
// with the ability to set a custom HTTPClient for a request.
func NewActDeviceAPIServiceListDevicesV1ParamsWithHTTPClient(client *http.Client) *ActDeviceAPIServiceListDevicesV1Params {
	return &ActDeviceAPIServiceListDevicesV1Params{
		HTTPClient: client,
	}
}

/*
ActDeviceAPIServiceListDevicesV1Params contains all the parameters to send to the API endpoint

	for the act device Api service list devices v1 operation.

	Typically these are written to a http.Request.
*/
type ActDeviceAPIServiceListDevicesV1Params struct {

	// Page.
	//
	// Format: uint64
	Page *string

	// PerPage.
	//
	// Format: uint64
	PerPage *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the act device Api service list devices v1 params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ActDeviceAPIServiceListDevicesV1Params) WithDefaults() *ActDeviceAPIServiceListDevicesV1Params {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the act device Api service list devices v1 params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ActDeviceAPIServiceListDevicesV1Params) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the act device Api service list devices v1 params
func (o *ActDeviceAPIServiceListDevicesV1Params) WithTimeout(timeout time.Duration) *ActDeviceAPIServiceListDevicesV1Params {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the act device Api service list devices v1 params
func (o *ActDeviceAPIServiceListDevicesV1Params) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the act device Api service list devices v1 params
func (o *ActDeviceAPIServiceListDevicesV1Params) WithContext(ctx context.Context) *ActDeviceAPIServiceListDevicesV1Params {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the act device Api service list devices v1 params
func (o *ActDeviceAPIServiceListDevicesV1Params) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the act device Api service list devices v1 params
func (o *ActDeviceAPIServiceListDevicesV1Params) WithHTTPClient(client *http.Client) *ActDeviceAPIServiceListDevicesV1Params {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the act device Api service list devices v1 params
func (o *ActDeviceAPIServiceListDevicesV1Params) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithPage adds the page to the act device Api service list devices v1 params
func (o *ActDeviceAPIServiceListDevicesV1Params) WithPage(page *string) *ActDeviceAPIServiceListDevicesV1Params {
	o.SetPage(page)
	return o
}

// SetPage adds the page to the act device Api service list devices v1 params
func (o *ActDeviceAPIServiceListDevicesV1Params) SetPage(page *string) {
	o.Page = page
}

// WithPerPage adds the perPage to the act device Api service list devices v1 params
func (o *ActDeviceAPIServiceListDevicesV1Params) WithPerPage(perPage *string) *ActDeviceAPIServiceListDevicesV1Params {
	o.SetPerPage(perPage)
	return o
}

// SetPerPage adds the perPage to the act device Api service list devices v1 params
func (o *ActDeviceAPIServiceListDevicesV1Params) SetPerPage(perPage *string) {
	o.PerPage = perPage
}

// WriteToRequest writes these params to a swagger request
func (o *ActDeviceAPIServiceListDevicesV1Params) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Page != nil {

		// query param page
		var qrPage string

		if o.Page != nil {
			qrPage = *o.Page
		}
		qPage := qrPage
		if qPage != "" {

			if err := r.SetQueryParam("page", qPage); err != nil {
				return err
			}
		}
	}

	if o.PerPage != nil {

		// query param perPage
		var qrPerPage string

		if o.PerPage != nil {
			qrPerPage = *o.PerPage
		}
		qPerPage := qrPerPage
		if qPerPage != "" {

			if err := r.SetQueryParam("perPage", qPerPage); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
