// Code generated by go-swagger; DO NOT EDIT.

package act_device_api_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/ozonmp/act-device-api/homework/hw2/test/http_clients/generated_client/models"
)

// ActDeviceAPIServiceRemoveDeviceV1Reader is a Reader for the ActDeviceAPIServiceRemoveDeviceV1 structure.
type ActDeviceAPIServiceRemoveDeviceV1Reader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ActDeviceAPIServiceRemoveDeviceV1Reader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewActDeviceAPIServiceRemoveDeviceV1OK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewActDeviceAPIServiceRemoveDeviceV1Default(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewActDeviceAPIServiceRemoveDeviceV1OK creates a ActDeviceAPIServiceRemoveDeviceV1OK with default headers values
func NewActDeviceAPIServiceRemoveDeviceV1OK() *ActDeviceAPIServiceRemoveDeviceV1OK {
	return &ActDeviceAPIServiceRemoveDeviceV1OK{}
}

/*
ActDeviceAPIServiceRemoveDeviceV1OK describes a response with status code 200, with default header values.

A successful response.
*/
type ActDeviceAPIServiceRemoveDeviceV1OK struct {
	Payload *models.V1RemoveDeviceV1Response
}

// IsSuccess returns true when this act device Api service remove device v1 o k response has a 2xx status code
func (o *ActDeviceAPIServiceRemoveDeviceV1OK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this act device Api service remove device v1 o k response has a 3xx status code
func (o *ActDeviceAPIServiceRemoveDeviceV1OK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this act device Api service remove device v1 o k response has a 4xx status code
func (o *ActDeviceAPIServiceRemoveDeviceV1OK) IsClientError() bool {
	return false
}

// IsServerError returns true when this act device Api service remove device v1 o k response has a 5xx status code
func (o *ActDeviceAPIServiceRemoveDeviceV1OK) IsServerError() bool {
	return false
}

// IsCode returns true when this act device Api service remove device v1 o k response a status code equal to that given
func (o *ActDeviceAPIServiceRemoveDeviceV1OK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the act device Api service remove device v1 o k response
func (o *ActDeviceAPIServiceRemoveDeviceV1OK) Code() int {
	return 200
}

func (o *ActDeviceAPIServiceRemoveDeviceV1OK) Error() string {
	return fmt.Sprintf("[DELETE /api/v1/devices/{deviceId}][%d] actDeviceApiServiceRemoveDeviceV1OK  %+v", 200, o.Payload)
}

func (o *ActDeviceAPIServiceRemoveDeviceV1OK) String() string {
	return fmt.Sprintf("[DELETE /api/v1/devices/{deviceId}][%d] actDeviceApiServiceRemoveDeviceV1OK  %+v", 200, o.Payload)
}

func (o *ActDeviceAPIServiceRemoveDeviceV1OK) GetPayload() *models.V1RemoveDeviceV1Response {
	return o.Payload
}

func (o *ActDeviceAPIServiceRemoveDeviceV1OK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V1RemoveDeviceV1Response)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewActDeviceAPIServiceRemoveDeviceV1Default creates a ActDeviceAPIServiceRemoveDeviceV1Default with default headers values
func NewActDeviceAPIServiceRemoveDeviceV1Default(code int) *ActDeviceAPIServiceRemoveDeviceV1Default {
	return &ActDeviceAPIServiceRemoveDeviceV1Default{
		_statusCode: code,
	}
}

/*
ActDeviceAPIServiceRemoveDeviceV1Default describes a response with status code -1, with default header values.

An unexpected error response.
*/
type ActDeviceAPIServiceRemoveDeviceV1Default struct {
	_statusCode int

	Payload *models.RPCStatus
}

// IsSuccess returns true when this act device Api service remove device v1 default response has a 2xx status code
func (o *ActDeviceAPIServiceRemoveDeviceV1Default) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this act device Api service remove device v1 default response has a 3xx status code
func (o *ActDeviceAPIServiceRemoveDeviceV1Default) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this act device Api service remove device v1 default response has a 4xx status code
func (o *ActDeviceAPIServiceRemoveDeviceV1Default) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this act device Api service remove device v1 default response has a 5xx status code
func (o *ActDeviceAPIServiceRemoveDeviceV1Default) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this act device Api service remove device v1 default response a status code equal to that given
func (o *ActDeviceAPIServiceRemoveDeviceV1Default) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the act device Api service remove device v1 default response
func (o *ActDeviceAPIServiceRemoveDeviceV1Default) Code() int {
	return o._statusCode
}

func (o *ActDeviceAPIServiceRemoveDeviceV1Default) Error() string {
	return fmt.Sprintf("[DELETE /api/v1/devices/{deviceId}][%d] ActDeviceApiService_RemoveDeviceV1 default  %+v", o._statusCode, o.Payload)
}

func (o *ActDeviceAPIServiceRemoveDeviceV1Default) String() string {
	return fmt.Sprintf("[DELETE /api/v1/devices/{deviceId}][%d] ActDeviceApiService_RemoveDeviceV1 default  %+v", o._statusCode, o.Payload)
}

func (o *ActDeviceAPIServiceRemoveDeviceV1Default) GetPayload() *models.RPCStatus {
	return o.Payload
}

func (o *ActDeviceAPIServiceRemoveDeviceV1Default) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RPCStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
