// Code generated by go-swagger; DO NOT EDIT.

package act_device_api_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/ozonmp/act-device-api/homework/hw2/test/http_clients/generated_client/models"
)

// NewActDeviceAPIServiceCreateDeviceV1Params creates a new ActDeviceAPIServiceCreateDeviceV1Params object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewActDeviceAPIServiceCreateDeviceV1Params() *ActDeviceAPIServiceCreateDeviceV1Params {
	return &ActDeviceAPIServiceCreateDeviceV1Params{
		timeout: cr.DefaultTimeout,
	}
}

// NewActDeviceAPIServiceCreateDeviceV1ParamsWithTimeout creates a new ActDeviceAPIServiceCreateDeviceV1Params object
// with the ability to set a timeout on a request.
func NewActDeviceAPIServiceCreateDeviceV1ParamsWithTimeout(timeout time.Duration) *ActDeviceAPIServiceCreateDeviceV1Params {
	return &ActDeviceAPIServiceCreateDeviceV1Params{
		timeout: timeout,
	}
}

// NewActDeviceAPIServiceCreateDeviceV1ParamsWithContext creates a new ActDeviceAPIServiceCreateDeviceV1Params object
// with the ability to set a context for a request.
func NewActDeviceAPIServiceCreateDeviceV1ParamsWithContext(ctx context.Context) *ActDeviceAPIServiceCreateDeviceV1Params {
	return &ActDeviceAPIServiceCreateDeviceV1Params{
		Context: ctx,
	}
}

// NewActDeviceAPIServiceCreateDeviceV1ParamsWithHTTPClient creates a new ActDeviceAPIServiceCreateDeviceV1Params object
// with the ability to set a custom HTTPClient for a request.
func NewActDeviceAPIServiceCreateDeviceV1ParamsWithHTTPClient(client *http.Client) *ActDeviceAPIServiceCreateDeviceV1Params {
	return &ActDeviceAPIServiceCreateDeviceV1Params{
		HTTPClient: client,
	}
}

/*
ActDeviceAPIServiceCreateDeviceV1Params contains all the parameters to send to the API endpoint

	for the act device Api service create device v1 operation.

	Typically these are written to a http.Request.
*/
type ActDeviceAPIServiceCreateDeviceV1Params struct {

	// Body.
	Body *models.V1CreateDeviceV1Request

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the act device Api service create device v1 params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ActDeviceAPIServiceCreateDeviceV1Params) WithDefaults() *ActDeviceAPIServiceCreateDeviceV1Params {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the act device Api service create device v1 params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ActDeviceAPIServiceCreateDeviceV1Params) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the act device Api service create device v1 params
func (o *ActDeviceAPIServiceCreateDeviceV1Params) WithTimeout(timeout time.Duration) *ActDeviceAPIServiceCreateDeviceV1Params {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the act device Api service create device v1 params
func (o *ActDeviceAPIServiceCreateDeviceV1Params) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the act device Api service create device v1 params
func (o *ActDeviceAPIServiceCreateDeviceV1Params) WithContext(ctx context.Context) *ActDeviceAPIServiceCreateDeviceV1Params {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the act device Api service create device v1 params
func (o *ActDeviceAPIServiceCreateDeviceV1Params) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the act device Api service create device v1 params
func (o *ActDeviceAPIServiceCreateDeviceV1Params) WithHTTPClient(client *http.Client) *ActDeviceAPIServiceCreateDeviceV1Params {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the act device Api service create device v1 params
func (o *ActDeviceAPIServiceCreateDeviceV1Params) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the act device Api service create device v1 params
func (o *ActDeviceAPIServiceCreateDeviceV1Params) WithBody(body *models.V1CreateDeviceV1Request) *ActDeviceAPIServiceCreateDeviceV1Params {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the act device Api service create device v1 params
func (o *ActDeviceAPIServiceCreateDeviceV1Params) SetBody(body *models.V1CreateDeviceV1Request) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *ActDeviceAPIServiceCreateDeviceV1Params) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
